class NestedError(BaseException):
    pass


class DeletionError(NestedError):
    pass
